//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForAoap.ServiceReferenceadd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://c.b.a", ConfigurationName="ServiceReferenceadd.CalculatorPortType")]
    public interface CalculatorPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:add", ReplyAction="urn:addResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int add(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:add", ReplyAction="urn:addResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> addAsync(int n1, int n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorPortTypeChannel : ConsoleAppForAoap.ServiceReferenceadd.CalculatorPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorPortTypeClient : System.ServiceModel.ClientBase<ConsoleAppForAoap.ServiceReferenceadd.CalculatorPortType>, ConsoleAppForAoap.ServiceReferenceadd.CalculatorPortType {
        
        public CalculatorPortTypeClient() {
        }
        
        public CalculatorPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int add(int n1, int n2) {
            return base.Channel.add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> addAsync(int n1, int n2) {
            return base.Channel.addAsync(n1, n2);
        }
    }
}
