//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForAoap.ServiceReferenceBANADER {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiRequestModel", Namespace="http://schemas.datacontract.org/2004/07/Massan.Models.Core")]
    [System.SerializableAttribute()]
    public partial class ApiRequestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ConsoleAppForAoap.ServiceReferenceBANADER.CallerCredential CredentialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppForAoap.ServiceReferenceBANADER.ApiServiceParameterModel[] ParametersField;
        
        private string ServiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleAppForAoap.ServiceReferenceBANADER.CallerCredential Credential {
            get {
                return this.CredentialField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialField, value) != true)) {
                    this.CredentialField = value;
                    this.RaisePropertyChanged("Credential");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleAppForAoap.ServiceReferenceBANADER.ApiServiceParameterModel[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallerCredential", Namespace="http://schemas.datacontract.org/2004/07/Massan.Models.Core")]
    [System.SerializableAttribute()]
    public partial class CallerCredential : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiServiceParameterModel", Namespace="http://schemas.datacontract.org/2004/07/Massan.Models.Core")]
    [System.SerializableAttribute()]
    public partial class ApiServiceParameterModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ParameterNameField;
        
        private string ParameterValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ParameterName {
            get {
                return this.ParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterNameField, value) != true)) {
                    this.ParameterNameField = value;
                    this.RaisePropertyChanged("ParameterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ParameterValue {
            get {
                return this.ParameterValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterValueField, value) != true)) {
                    this.ParameterValueField = value;
                    this.RaisePropertyChanged("ParameterValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResponseModel", Namespace="http://schemas.datacontract.org/2004/07/Massan.Models.Core")]
    [System.SerializableAttribute()]
    public partial class ApiResponseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppForAoap.ServiceReferenceBANADER.KeyValuePairOfStringString[] CookiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DigitalSignatureField;
        
        private System.Nullable<ConsoleAppForAoap.ServiceReferenceBANADER.InvokeErrors> ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResponseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppForAoap.ServiceReferenceBANADER.KeyValuePairOfStringString[] ResponseHeadersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppForAoap.ServiceReferenceBANADER.UsedQuotaStats UsedQuotaStatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkerDebugLogField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleAppForAoap.ServiceReferenceBANADER.KeyValuePairOfStringString[] Cookies {
            get {
                return this.CookiesField;
            }
            set {
                if ((object.ReferenceEquals(this.CookiesField, value) != true)) {
                    this.CookiesField = value;
                    this.RaisePropertyChanged("Cookies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DigitalSignature {
            get {
                return this.DigitalSignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.DigitalSignatureField, value) != true)) {
                    this.DigitalSignatureField = value;
                    this.RaisePropertyChanged("DigitalSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ConsoleAppForAoap.ServiceReferenceBANADER.InvokeErrors> Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseDate {
            get {
                return this.ResponseDateField;
            }
            set {
                if ((this.ResponseDateField.Equals(value) != true)) {
                    this.ResponseDateField = value;
                    this.RaisePropertyChanged("ResponseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleAppForAoap.ServiceReferenceBANADER.KeyValuePairOfStringString[] ResponseHeaders {
            get {
                return this.ResponseHeadersField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseHeadersField, value) != true)) {
                    this.ResponseHeadersField = value;
                    this.RaisePropertyChanged("ResponseHeaders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseStatusCode {
            get {
                return this.ResponseStatusCodeField;
            }
            set {
                if ((this.ResponseStatusCodeField.Equals(value) != true)) {
                    this.ResponseStatusCodeField = value;
                    this.RaisePropertyChanged("ResponseStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseText {
            get {
                return this.ResponseTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseTextField, value) != true)) {
                    this.ResponseTextField = value;
                    this.RaisePropertyChanged("ResponseText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleAppForAoap.ServiceReferenceBANADER.UsedQuotaStats UsedQuotaStats {
            get {
                return this.UsedQuotaStatsField;
            }
            set {
                if ((object.ReferenceEquals(this.UsedQuotaStatsField, value) != true)) {
                    this.UsedQuotaStatsField = value;
                    this.RaisePropertyChanged("UsedQuotaStats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkerDebugLog {
            get {
                return this.WorkerDebugLogField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerDebugLogField, value) != true)) {
                    this.WorkerDebugLogField = value;
                    this.RaisePropertyChanged("WorkerDebugLog");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsedQuotaStats", Namespace="http://schemas.datacontract.org/2004/07/Massan.Models.Core")]
    [System.SerializableAttribute()]
    public partial class UsedQuotaStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DailyUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HourlyUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutelyUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthlyUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecondlyUsedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DailyUsed {
            get {
                return this.DailyUsedField;
            }
            set {
                if ((this.DailyUsedField.Equals(value) != true)) {
                    this.DailyUsedField = value;
                    this.RaisePropertyChanged("DailyUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HourlyUsed {
            get {
                return this.HourlyUsedField;
            }
            set {
                if ((this.HourlyUsedField.Equals(value) != true)) {
                    this.HourlyUsedField = value;
                    this.RaisePropertyChanged("HourlyUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinutelyUsed {
            get {
                return this.MinutelyUsedField;
            }
            set {
                if ((this.MinutelyUsedField.Equals(value) != true)) {
                    this.MinutelyUsedField = value;
                    this.RaisePropertyChanged("MinutelyUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthlyUsed {
            get {
                return this.MonthlyUsedField;
            }
            set {
                if ((this.MonthlyUsedField.Equals(value) != true)) {
                    this.MonthlyUsedField = value;
                    this.RaisePropertyChanged("MonthlyUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecondlyUsed {
            get {
                return this.SecondlyUsedField;
            }
            set {
                if ((this.SecondlyUsedField.Equals(value) != true)) {
                    this.SecondlyUsedField = value;
                    this.RaisePropertyChanged("SecondlyUsed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfStringString", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    [System.SerializableAttribute()]
    public partial struct KeyValuePairOfStringString : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        public static implicit operator ExtensionDataObject(KeyValuePairOfStringString v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvokeErrors", Namespace="http://schemas.datacontract.org/2004/07/Massan.Models")]
    public enum InvokeErrors : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerIsDisabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerInvalidSecret = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerNotAccess = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerExceedQuota = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerUnknownQuota = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceNotFound = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceDisabled = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConsumerInvalidIp = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RateLimitExceeded = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DosAttackRecognized = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BlackListIp = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaxResponseLengthReached = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParameterMissed = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParameterTypeMismatched = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timeout = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkerConnectToServiceError = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NullResponse = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnhandledError = 19,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBANADER.MassanSoapServiceProvider")]
    public interface MassanSoapServiceProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassanSoapServiceProvider/Invoke", ReplyAction="http://tempuri.org/MassanSoapServiceProvider/InvokeResponse")]
        ConsoleAppForAoap.ServiceReferenceBANADER.ApiResponseModel Invoke(ConsoleAppForAoap.ServiceReferenceBANADER.ApiRequestModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MassanSoapServiceProvider/Invoke", ReplyAction="http://tempuri.org/MassanSoapServiceProvider/InvokeResponse")]
        System.Threading.Tasks.Task<ConsoleAppForAoap.ServiceReferenceBANADER.ApiResponseModel> InvokeAsync(ConsoleAppForAoap.ServiceReferenceBANADER.ApiRequestModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MassanSoapServiceProviderChannel : ConsoleAppForAoap.ServiceReferenceBANADER.MassanSoapServiceProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MassanSoapServiceProviderClient : System.ServiceModel.ClientBase<ConsoleAppForAoap.ServiceReferenceBANADER.MassanSoapServiceProvider>, ConsoleAppForAoap.ServiceReferenceBANADER.MassanSoapServiceProvider {
        
        public MassanSoapServiceProviderClient() {
        }
        
        public MassanSoapServiceProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MassanSoapServiceProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MassanSoapServiceProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MassanSoapServiceProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleAppForAoap.ServiceReferenceBANADER.ApiResponseModel Invoke(ConsoleAppForAoap.ServiceReferenceBANADER.ApiRequestModel model) {
            return base.Channel.Invoke(model);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppForAoap.ServiceReferenceBANADER.ApiResponseModel> InvokeAsync(ConsoleAppForAoap.ServiceReferenceBANADER.ApiRequestModel model) {
            return base.Channel.InvokeAsync(model);
        }
    }
}
